"""afegim posts a la db

Revision ID: e10d32a6123e
Revises: 09f6bdec82a5
Create Date: 2022-02-26 20:34:33.202457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10d32a6123e'
down_revision = '09f6bdec82a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=False),
    sa.Column('data_publicacio', sa.DateTime(), nullable=True),
    sa.Column('contingut', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
